from .users import Users as UsersResource
from .user import User as UserResource
from .notificaciones import Notificaciones as NotificacionesResource
from .valoraciones import Valoraciones as ValoracionesResource
from .valoracion import Valoracion as ValoracionResource
from .products import Products as ProductsResource
from .product import Product as ProductResource
from .pedidos import Pedidos as PedidosResource
from .pedido import Pedido as PedidoResource
from .login import LogIn as LogInResource
from .logout import LogOut as LogOutResource
from .categorias import Categorias as CategoriasResource
from .categoria import Categoria as CategoriaResource
from .facturas import Facturas as FacturasResource
from .factura import Factura as FacturaResource
from .notificacion import Notificacion as NotificacionResource