from .pollo import Users as UsersResource
from .pollo import User as UserResource
from .pollo import Notificaciones as NotificacionesResource
from .pollo import Valoracion as ValoracionResource
from .pollo import Products as ProductsResource
from .pollo import Product as ProductResource
from .pollo import Pedidos as PedidosResource
from .pollo import Pedido as PedidoResource
from .pollo import LogIn as LogInResource
from .pollo import LogOut as LogOutResource